export interface Country {
  code: string;
  name: string;
  prefix: string;
  flag: string;
}

export const COUNTRIES: Country[] = [
  { code: 'ES', name: 'España', prefix: '+34', flag: '🇪🇸' },
  { code: 'US', name: 'Estados Unidos', prefix: '+1', flag: '🇺🇸' },
  { code: 'MX', name: 'México', prefix: '+52', flag: '🇲🇽' },
  { code: 'AR', name: 'Argentina', prefix: '+54', flag: '🇦🇷' },
  { code: 'CO', name: 'Colombia', prefix: '+57', flag: '🇨🇴' },
  { code: 'CL', name: 'Chile', prefix: '+56', flag: '🇨🇱' },
  { code: 'PE', name: 'Perú', prefix: '+51', flag: '🇵🇪' },
  { code: 'VE', name: 'Venezuela', prefix: '+58', flag: '🇻🇪' },
  { code: 'BR', name: 'Brasil', prefix: '+55', flag: '🇧🇷' },
  { code: 'UY', name: 'Uruguay', prefix: '+598', flag: '🇺🇾' },
  { code: 'PY', name: 'Paraguay', prefix: '+595', flag: '🇵🇾' },
  { code: 'BO', name: 'Bolivia', prefix: '+591', flag: '🇧🇴' },
  { code: 'EC', name: 'Ecuador', prefix: '+593', flag: '🇪🇨' },
  { code: 'CR', name: 'Costa Rica', prefix: '+506', flag: '🇨🇷' },
  { code: 'DO', name: 'Rep. Dominicana', prefix: '+1', flag: '🇩🇴' },
  { code: 'GT', name: 'Guatemala', prefix: '+502', flag: '🇬🇹' },
  { code: 'HN', name: 'Honduras', prefix: '+504', flag: '🇭🇳' },
  { code: 'NI', name: 'Nicaragua', prefix: '+505', flag: '🇳🇮' },
  { code: 'PA', name: 'Panamá', prefix: '+507', flag: '🇵🇦' },
  { code: 'SV', name: 'El Salvador', prefix: '+503', flag: '🇸🇻' },
  { code: 'CU', name: 'Cuba', prefix: '+53', flag: '🇨🇺' },
  { code: 'PR', name: 'Puerto Rico', prefix: '+1', flag: '🇵🇷' },
  { code: 'FR', name: 'Francia', prefix: '+33', flag: '🇫🇷' },
  { code: 'DE', name: 'Alemania', prefix: '+49', flag: '🇩🇪' },
  { code: 'IT', name: 'Italia', prefix: '+39', flag: '🇮🇹' },
  { code: 'GB', name: 'Reino Unido', prefix: '+44', flag: '🇬🇧' },
  { code: 'PT', name: 'Portugal', prefix: '+351', flag: '🇵🇹' },
  { code: 'NL', name: 'Países Bajos', prefix: '+31', flag: '🇳🇱' },
  { code: 'BE', name: 'Bélgica', prefix: '+32', flag: '🇧🇪' },
  { code: 'CH', name: 'Suiza', prefix: '+41', flag: '🇨🇭' },
  { code: 'AT', name: 'Austria', prefix: '+43', flag: '🇦🇹' },
  { code: 'SE', name: 'Suecia', prefix: '+46', flag: '🇸🇪' },
  { code: 'NO', name: 'Noruega', prefix: '+47', flag: '🇳🇴' },
  { code: 'DK', name: 'Dinamarca', prefix: '+45', flag: '🇩🇰' },
  { code: 'FI', name: 'Finlandia', prefix: '+358', flag: '🇫🇮' },
  { code: 'IE', name: 'Irlanda', prefix: '+353', flag: '🇮🇪' },
  { code: 'PL', name: 'Polonia', prefix: '+48', flag: '🇵🇱' },
  { code: 'CZ', name: 'Rep. Checa', prefix: '+420', flag: '🇨🇿' },
  { code: 'HU', name: 'Hungría', prefix: '+36', flag: '🇭🇺' },
  { code: 'RO', name: 'Rumania', prefix: '+40', flag: '🇷🇴' },
  { code: 'BG', name: 'Bulgaria', prefix: '+359', flag: '🇧🇬' },
  { code: 'HR', name: 'Croacia', prefix: '+385', flag: '🇭🇷' },
  { code: 'SI', name: 'Eslovenia', prefix: '+386', flag: '🇸🇮' },
  { code: 'SK', name: 'Eslovaquia', prefix: '+421', flag: '🇸🇰' },
  { code: 'GR', name: 'Grecia', prefix: '+30', flag: '🇬🇷' },
  { code: 'CY', name: 'Chipre', prefix: '+357', flag: '🇨🇾' },
  { code: 'MT', name: 'Malta', prefix: '+356', flag: '🇲🇹' },
  { code: 'LU', name: 'Luxemburgo', prefix: '+352', flag: '🇱🇺' },
  { code: 'EE', name: 'Estonia', prefix: '+372', flag: '🇪🇪' },
  { code: 'LV', name: 'Letonia', prefix: '+371', flag: '🇱🇻' },
  { code: 'LT', name: 'Lituania', prefix: '+370', flag: '🇱🇹' },
  { code: 'RU', name: 'Rusia', prefix: '+7', flag: '🇷🇺' },
  { code: 'UA', name: 'Ucrania', prefix: '+380', flag: '🇺🇦' },
  { code: 'TR', name: 'Turquía', prefix: '+90', flag: '🇹🇷' },
  { code: 'IN', name: 'India', prefix: '+91', flag: '🇮🇳' },
  { code: 'CN', name: 'China', prefix: '+86', flag: '🇨🇳' },
  { code: 'JP', name: 'Japón', prefix: '+81', flag: '🇯🇵' },
  { code: 'KR', name: 'Corea del Sur', prefix: '+82', flag: '🇰🇷' },
  { code: 'ID', name: 'Indonesia', prefix: '+62', flag: '🇮🇩' },
  { code: 'TH', name: 'Tailandia', prefix: '+66', flag: '🇹🇭' },
  { code: 'VN', name: 'Vietnam', prefix: '+84', flag: '🇻🇳' },
  { code: 'MY', name: 'Malasia', prefix: '+60', flag: '🇲🇾' },
  { code: 'PH', name: 'Filipinas', prefix: '+63', flag: '🇵🇭' },
  { code: 'SG', name: 'Singapur', prefix: '+65', flag: '🇸🇬' },
  { code: 'AU', name: 'Australia', prefix: '+61', flag: '🇦🇺' },
  { code: 'NZ', name: 'Nueva Zelanda', prefix: '+64', flag: '🇳🇿' },
  { code: 'ZA', name: 'Sudáfrica', prefix: '+27', flag: '🇿🇦' },
  { code: 'EG', name: 'Egipto', prefix: '+20', flag: '🇪🇬' },
  { code: 'NG', name: 'Nigeria', prefix: '+234', flag: '🇳🇬' },
  { code: 'KE', name: 'Kenia', prefix: '+254', flag: '🇰🇪' },
  { code: 'MA', name: 'Marruecos', prefix: '+212', flag: '🇲🇦' },
  { code: 'TN', name: 'Túnez', prefix: '+216', flag: '🇹🇳' },
  { code: 'DZ', name: 'Argelia', prefix: '+213', flag: '🇩🇿' },
  { code: 'IL', name: 'Israel', prefix: '+972', flag: '🇮🇱' },
  { code: 'SA', name: 'Arabia Saudita', prefix: '+966', flag: '🇸🇦' },
  { code: 'AE', name: 'Emiratos Árabes', prefix: '+971', flag: '🇦🇪' },
  { code: 'QA', name: 'Qatar', prefix: '+974', flag: '🇶🇦' },
  { code: 'KW', name: 'Kuwait', prefix: '+965', flag: '🇰🇼' },
  { code: 'BH', name: 'Baréin', prefix: '+973', flag: '🇧🇭' },
  { code: 'OM', name: 'Omán', prefix: '+968', flag: '🇴🇲' },
  { code: 'JO', name: 'Jordania', prefix: '+962', flag: '🇯🇴' },
  { code: 'LB', name: 'Líbano', prefix: '+961', flag: '🇱🇧' },
  { code: 'IQ', name: 'Irak', prefix: '+964', flag: '🇮🇶' },
  { code: 'IR', name: 'Irán', prefix: '+98', flag: '🇮🇷' },
  { code: 'PK', name: 'Pakistán', prefix: '+92', flag: '🇵🇰' },
  { code: 'BD', name: 'Bangladesh', prefix: '+880', flag: '🇧🇩' },
  { code: 'LK', name: 'Sri Lanka', prefix: '+94', flag: '🇱🇰' },
  { code: 'NP', name: 'Nepal', prefix: '+977', flag: '🇳🇵' },
  { code: 'MM', name: 'Myanmar', prefix: '+95', flag: '🇲🇲' },
  { code: 'KH', name: 'Camboya', prefix: '+855', flag: '🇰🇭' },
  { code: 'LA', name: 'Laos', prefix: '+856', flag: '🇱🇦' },
  { code: 'BN', name: 'Brunéi', prefix: '+673', flag: '🇧🇳' },
  { code: 'MO', name: 'Macao', prefix: '+853', flag: '🇲🇴' },
  { code: 'HK', name: 'Hong Kong', prefix: '+852', flag: '🇭🇰' },
  { code: 'TW', name: 'Taiwán', prefix: '+886', flag: '🇹🇼' },
  { code: 'CA', name: 'Canadá', prefix: '+1', flag: '🇨🇦' },
];
